spring:
  application:
    name: stock-processor-api
  kafka:
    streams:
      application-id: stock-kstream
      bootstrap-servers: broker-10.broker.kafka.svc.cluster.local:9092,broker-11.broker.kafka.svc.cluster.local:9092,broker-12.broker.kafka.svc.cluster.local:9092
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
        schema.registry.url: http://schema-reg.kafka.svc.cluster.local:8081
        num.partitions: 10

logging:
  level:
    org.apache.kafka.streams.processor.internals.StreamThread: info
    org.apache.kafka.streams.processor.internals.StoreChangelogReader: info
    org.apache.kafka.streams.processor: debug
    org.apache.kafka.streams.state: debug