apiVersion: v2
name: confluent-platform
version: 1.0.0
description: Helm Chart for Confluent platform
type: application
keywords:
- kafka-cluster-kcraft
- kafka-connect
- kafka-schema-registry
- debezium-postgres-source-connector
home: https://github.com/kwonghung-YIP
maintainers:
- name: Hung YIP
  email: kwonghung.yip@gmail.com
appVersion: "7.5.3"