apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: spring-boot-apps
build:
  insecureRegistries:
  - "localhost:32000"
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
  - image: localhost:32000/kwonghung/stock-kstream
    context: ./stock-kstream
    custom:
      # $IMAGE is set by skaffold included the temporary tag
      # https://skaffold.dev/docs/builders/builder-types/custom/
      buildCommand: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE -DskipTests
  - image: localhost:32000/kwonghung/stock-processor-api
    context: ./stock-processor-api
    custom:
      # $IMAGE is set by skaffold included the temporary tag
      # https://skaffold.dev/docs/builders/builder-types/custom/
      buildCommand: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE -DskipTests
deploy:
  helm:
    releases:
      - name: spring-boot-apps
        chartPath: ./helm
        version: 1.0.0
        namespace: default
        setValueTemplates:
          stock_kstream.image.tag: "{{.IMAGE_TAG_localhost_32000_kwonghung_stock_kstream }}@{{.IMAGE_DIGEST_localhost_32000_kwonghung_stock_kstream }}"
          stock_processor_api.image.tag: "{{.IMAGE_TAG_localhost_32000_kwonghung_stock_processor_api }}@{{.IMAGE_DIGEST_localhost_32000_kwonghung_stock_processor_api }}"
