apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        {{- with .Values.postgres.image }}
        image: {{ .registry }}/{{ .name }}:{{ .tag }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
        - name: init-sql
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
      volumes:
      - name: init-sql
        configMap:
          name: postgres-config
          items:
          - key: "stock-init.sql"
            path: "stock-init.sql"